### ISSUE TITLE
Closing modal leaves carousel buttons

### ISSUE THREAD

**Issue by jsblair9** [LionsMouthDigital/vue-hex-modals#1]
When the modal is opened, closing the modal via the `X` only removes the modal message div, but leaves the carousel next/previous buttons. Selecting one of the next/previous buttons does bring up the next modal div into view. 

Hitting `esc` does dismiss everything as expected

![hex-modal-error](https://cloud.githubusercontent.com/assets/4450975/14648873/0bbbcede-062a-11e6-8094-d45563cfe20e.gif)

**Comment by jsblair9** [comment]
it is very possible that this is an issue with this mastermind project specifically, as this behavior is not replicated on the kitchen sink page

**Comment by curtisblackwell** [comment]
Can't replicate, probably a lack of compiled code.
